name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O la rama que uses para desplegar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace Supabase credentials
        run: |
          sed -i "s|__SUPABASE_URL__|${{ secrets.SUPABASE_URL }}|g" supabaseClient.js
          sed -i "s|__SUPABASE_ANON_KEY__|${{ secrets.SUPABASE_ANON_KEY }}|g" supabaseClient.js
        
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
